language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install --dev
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit
  - phpcs --standard=psr2 src
  - vendor/bin/phpmd src text codesize
